GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZuYW1lIjoiQXlhbSIsImVtYWlsIjoiYXlhbUBnbWFpbC5jb20iLCJpYXQiOjE2NzcyMDcyNzcsImV4cCI6MTY3NzIwNzI5Mn0.8O-AIQUd23JfhfUGHn_0XJsxuc6atN_1Si39uBojpBA

###
GET http://localhost:5000/users/7959b951-e99b-4865-a6d1-7400fed48bc6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZuYW1lIjoiQXlhbSIsImVtYWlsIjoiYXlhbUBnbWFpbC5jb20iLCJpYXQiOjE2NzcyMDc1NTgsImV4cCI6MTY3NzIwNzU3M30.93q6ouvoubbiCTnkvMvNDQA3MZ3ubaN_Eqj3mCXX68A


POST http://localhost:5000/users
Content-Type: application/json

{
    "fname": "Ayam",
    "lname": "Adk",
    "email": "ayam@gmail.com",
    "contact": "9807991393",
    "role": "Tenant",
    "password": "123456",
    "confpassword": "123456"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ayam@gmail.com",
    "password": "123456"
}

###
GET  http://localhost:5000/token

###
DELETE   http://localhost:5000/logout

####
GET http://localhost:5000/users/eeb4d997-e62e-4394-9ce8-b0abe36ba68b