GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZuYW1lIjoiU2FoaWwiLCJlbWFpbCI6IlNhaGlsQGdtYWlsLmNvbSIsImlhdCI6MTY3NjU2Mjg3NywiZXhwIjoxNjc2NTYyODkyfQ.dbWWmuSePFOYxSOPglpQbISxcPj966GLzfMpMmtECz8

###
GET http://localhost:5000/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImZuYW1lIjoiU2FoaWwiLCJlbWFpbCI6InNhaGlsQGdtYWlsLmNvbSIsImxuYW1lIjoiQWRoaWthcmkiLCJyb2xlIjoiTGFuZGxvcmQiLCJpYXQiOjE2Nzg3OTE5NzksImV4cCI6MTY3ODg0NTk3OX0.Q7x1RjmSxHNik3-oQJebwkKrFVW5b-I2f2Uulqd8TS8


#####


POST http://localhost:5000/users
Content-Type: application/json

{
    "fname": "Sahil",
    "lname": "Adk",
    "email": "sahil@gmail.com",
    "contact": "9807991363",
    "role": "Tenant",
    "password":"12345",
    "confpassword":"12345",
    "location":"Baneswor"
}

###
POST http://localhost:5000/add
Content-Type: application/json

{
    "Name": "Sahil Adk",
    "Location": "Adk",
    "email": "Sahil@gmail.com",
    "contact": "9807991363"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Sahil@gmail.com",
    "password": "12345"
}

###
GET  http://localhost:5000/token

###
DELETE   http://localhost:5000/logout